language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t stoeck.de/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stoeck.de/docker-react npm run test